DROP TRIGGER IF EXISTS update_pegawai_timestamp;
DELIMITER //
CREATE TRIGGER update_pegawai_timestamp
BEFORE UPDATE ON pegawai
FOR EACH ROW
BEGIN
  SET NEW.updated_at = CURRENT_TIMESTAMP;
END //
DELIMITER ;
