SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE laporan_penggantian;
TRUNCATE TABLE dispenser;
TRUNCATE TABLE pegawai;
TRUNCATE TABLE lokasi;
TRUNCATE TABLE admin;
TRUNCATE TABLE login;
SET FOREIGN_KEY_CHECKS = 1;
